apiVersion: v2
name: devportal
description: Platform devportal helm chart.
type: application
version: "0.20.11"
appVersion: "0.7.1"
home: https://platform.vee.codes/
icon: https://platform.vee.codes/android-chrome-512x512.png
keywords:
- veecode
- platform
- devportal
- backstage
- api management
- idp
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: "2.31.3"
