dynamicPlugins:
  frontend:
    red-hat-developer-hub-backstage-plugin-global-header:
      app:
        sidebar:
          search: false
          settings: false
      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.create:
                title: ''
          red-hat-developer-hub.backstage-plugin-global-header:
            mountPoints:
              - mountPoint: application/header
                importName: GlobalHeader
                config:
                  position: above-main-content
              - mountPoint: global.header/component
                importName: SearchComponent
                config:
                  priority: 100
              - mountPoint: global.header/component
                importName: Spacer
                config:
                  priority: 99
                  props:
                    growFactor: 0
              - mountPoint: global.header/component
                importName: HeaderIconButton
                config:
                  priority: 90
                  props:
                    title: Self-service
                    icon: add
                    to: create
              - mountPoint: global.header/component
                importName: SupportButton
                config:
                  priority: 80
              - mountPoint: global.header/component
                importName: NotificationButton
                config:
                  priority: 70
              - mountPoint: global.header/component
                importName: Divider
                config:
                  priority: 50
              - mountPoint: global.header/component
                importName: ProfileDropdown
                config:
                  priority: 10
              - mountPoint: global.header/profile
                importName: MenuItemLink
                config:
                  priority: 100
                  props:
                    title: Settings
                    link: /settings
                    icon: manageAccounts
              - mountPoint: global.header/profile
                importName: LogoutButton
                config:
                  priority: 10
    red-hat-developer-hub-backstage-plugin-global-floating-action-button:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-global-floating-action-button:
            mountPoints:
              - mountPoint: application/listener
                importName: DynamicGlobalFloatingActionButton
    red-hat-developer-hub-backstage-plugin-dynamic-home-page:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-dynamic-home-page:
            dynamicRoutes:
              - path: /
                importName: DynamicHomePage
            mountPoints:
              - mountPoint: application/listener
                importName: VisitListener
              - mountPoint: home.page/cards
                importName: SearchBar
                config:
                  layouts:
                    xl:
                      w: 10
                      h: 1
                      x: 1
                    lg:
                      w: 10
                      h: 1
                      x: 1
                    md:
                      w: 10
                      h: 1
                      x: 1
                    sm:
                      w: 10
                      h: 1
                      x: 1
                    xs:
                      w: 12
                      h: 1
                    xxs:
                      w: 12
                      h: 1
              - mountPoint: home.page/cards
                importName: QuickAccessCard
                config:
                  layouts:
                    xl:
                      w: 7
                      h: 8
                    lg:
                      w: 7
                      h: 8
                    md:
                      w: 7
                      h: 8
                    sm:
                      w: 12
                      h: 8
                    xs:
                      w: 12
                      h: 8
                    xxs:
                      w: 12
                      h: 8
              - mountPoint: home.page/cards
                importName: CatalogStarredEntitiesCard
                config:
                  layouts:
                    xl:
                      w: 5
                      h: 4
                      x: 7
                    lg:
                      w: 5
                      h: 4
                      x: 7
                    md:
                      w: 5
                      h: 4
                      x: 7
                    sm:
                      w: 12
                      h: 4
                    xs:
                      w: 12
                      h: 4
                    xxs:
                      w: 12
                      h: 4
