apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devportal-charts.fullname" . }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "devportal-charts.fullname" . }}
  {{- if .Values.hostAliases }}
  hostAliases:
  {{- range .Values.hostAliases }}
  - ip: {{ .ip }}
    hostnames:
    {{- range .hostnames }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "devportal-charts.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/devportal_configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/devportal_secret.yaml") . | sha256sum }}        
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "devportal-charts.fullname" . }}-credentials
            - configMapRef:
                name: {{ include "devportal-charts.fullname" . }}-app-env
          env:
            - name: NODE_ENV
              value: {{ .Values.environment | default "development" }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
          - name: app-config
            mountPath: /app/app-config.yaml
            subPath: app-config
          {{- if and .Values.theme.custom .Values.theme.custom.configmapName }}
          - name: platform-devportal-theme
            mountPath: /app/packages/app/dist/theme.json
            subPath: theme.json
          {{- end }}
          {{- if and .Values.integrations.github .Values.integrations.github.apps }}
          - name: platform-devportal-github-app
            mountPath: /app/github-app-credentials.yaml
            subPath: github-app-credentials
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
      volumes:
        - name: app-config
          configMap:
            name: "{{ include "devportal-charts.fullname" . }}-app-env"
        {{- if and .Values.theme.custom .Values.theme.custom.configmapName }}
        - name: platform-devportal-theme
          configMap:
            name: {{ .Values.theme.custom.configmapName }}
        {{- end }}
        {{- if and .Values.integrations.github .Values.integrations.github.apps }}
        - name: platform-devportal-github-app
          secret:
            {{- if .Values.integrations.github.apps.secretName }}
            secretName: {{ .Values.integrations.github.apps.secretName }}
            {{- else }}
            secretName: "{{ include "devportal-charts.fullname" . }}-github-app"
            {{- end }}
        {{- end }}
