{{ if and .Values.permission.rbac.enabled .Values.permission.rbac.admin.defaultAdminRoleEnabled }}
{{ $adminGroup := .Values.platform.defaultGroups.admin | default "platform-admin" }}
{{ $userGroup := .Values.platform.defaultGroups.user | default "platform-user" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "devportal-charts.fullname" . }}-roles-env"
data:
  rbac-policies: | 

    p, role:default/catalog, catalog.entity.read, read, allow
    p, role:default/catalog, catalog.entity.create, create, allow
    p, role:default/catalog, catalog.entity.delete, delete, allow
    p, role:default/catalog, catalog.entity.refresh, update, allow
    p, role:default/catalog, catalog.entity.validate, use, allow
    p, role:default/catalog, catalog.location.read, read, allow
    p, role:default/catalog, catalog.location.create, create, allow
    p, role:default/catalog, catalog.location.delete, delete, allow
    p, role:default/catalog, catalog.location.analyze, use, allow
    g, group:default/{{ $adminGroup }}, role:default/catalog


    p, role:default/scaffolder, scaffolder.task.cancel, use, allow
    p, role:default/scaffolder, scaffolder.task.create, create, allow
    p, role:default/scaffolder, scaffolder.task.read, read, allow
    p, role:default/scaffolder, scaffolder.template.parameter.read, read, allow
    p, role:default/scaffolder, scaffolder.template.step.read, read, allow
    p, role:default/scaffolder, scaffolder.action.execute, use, allow
    g, group:default/{{ $adminGroup }}, role:default/scaffolder


    p, role:default/policy, policy.entity.read, read, allow
    p, role:default/policy, policy.entity.create, create, allow
    p, role:default/policy, policy.entity.delete, delete, allow
    p, role:default/policy, policy.entity.update, update, allow
    g, group:default/{{ $adminGroup }}, role:default/policy


    p, role:default/kubernetes, kubernetes.proxy, use, allow
    g, group:default/{{ $adminGroup }}, role:default/kubernetes


    p, role:default/kong-service-manager, kong.service.read, read, allow
    p, role:default/kong-service-manager, kong.read.available.plugins, read, allow
    p, role:default/kong-service-manager, kong.routes.read, read, allow
    p, role:default/kong-service-manager, kong.apply.plugins.service, create, allow
    p, role:default/kong-service-manager, kong.update.service.plugin, update, allow
    p, role:default/kong-service-manager, kong.disable.service.plugin, delete, allow
    p, role:default/kong-service-manager, kong.route.create, create, allow
    p, role:default/kong-service-manager, kong.route.update, update, allow
    p, role:default/kong-service-manager, kong.route.delete, delete, allow
    p, role:default/kong-service-manager, kong.apply.plugins.route, create, allow
    p, role:default/kong-service-manager, kong.update.route.plugin, update, allow
    p, role:default/kong-service-manager, kong.disable.route.plugin, delete, allow
    p, role:default/kong-service-manager, kong.read.specs, read, allow
    p, role:default/kong-service-manager, kong.update.spec, update, allow
    p, role:default/kong-service-manager, kong.read.ai.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.auth.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.security.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.traffic.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.serverless.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.transform.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.logging.plugins, read, allow
    p, role:default/kong-service-manager, kong.read.analytics.plugins, read, allow
    g, group:default/{{ $adminGroup }}, role:default/kong-service-manager


    p, role:default/cluster-explorer, cluster.explorer.read, read, allow
    p, role:default/cluster-explorer, cluster.explorer.public.environment.read, read, allow
    g, group:default/{{ $adminGroup }}, role:default/cluster-explorer


    p, role:default/gitlab-pipelines, gitlab.pipelines.read, read, allow
    p, role:default/gitlab-pipelines, gitlab.pipelines.create, create, allow
    g, group:default/{{ $adminGroup }}, role:default/gitlab-pipelines


    p, role:default/github-workflows, github.workflows.read, read, allow
    p, role:default/github-workflows, github.workflows.create, create, allow
    g, group:default/{{ $adminGroup }}, role:default/github-workflows


    p, role:default/admin-api-management, admin.access.read, read, allow
    p, role:default/admin-api-management, apiManagement.access.read, read, allow
    g, group:default/{{ $adminGroup }}, role:default/admin-api-management



    p, role:default/github-guest, policy.entity.read, read, allow
    p, role:default/github-guest, catalog.entity.read, read, allow
    p, role:default/github-guest, catalog.location.read, read, allow
    p, role:default/github-guest, scaffolder.task.read, read, allow
    p, role:default/github-guest, scaffolder.template.parameter.read, read, allow
    p, role:default/github-guest, scaffolder.template.step.read, read, allow
    g, user:default/github-guest, role:default/github-guest

   
{{- end }}