
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devportal.serviceAccountName" . }}
  labels:
    {{- include "devportal-charts.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "devportal.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces", "api"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devportal.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "devportal.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "devportal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}