{{ if and (not .Values.platform.guest.enabled) .Values.permission.rbac.enabled .Values.permission.rbac.admin.defaultAdminRoleEnabled }}
{{ $adminGroup := .Values.platform.defaultGroups.admin | default "platform-admin" }}
{{ $userGroup := .Values.platform.defaultGroups.user | default "platform-user" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "devportal-charts.fullname" . }}-roles-env"
data:
  rbac-policies: | 
    p, role:default/devportal-admin, catalog-entity, read, allow
    p, role:default/devportal-admin, catalog.entity.create, create, allow
    p, role:default/devportal-admin, policy-entity, read, allow
    p, role:default/devportal-admin, policy-entity, create, allow
    p, role:default/devportal-admin, policy-entity, update, allow
    p, role:default/devportal-admin, policy-entity, delete, allow
    
    p, role:default/devportal-admin, catalog.entity.read, read, allow
    p, role:default/devportal-admin, catalog.entity.create, create, allow
    p, role:default/devportal-admin, catalog.entity.delete, delete, allow
    p, role:default/devportal-admin, catalog.entity.refresh, update, allow
    p, role:default/devportal-admin, catalog.entity.validate, use, allow
    p, role:default/devportal-admin, catalog.location.read, read, allow
    p, role:default/devportal-admin, catalog.location.create, create, allow
    p, role:default/devportal-admin, catalog.location.delete, delete, allow
    p, role:default/devportal-admin, catalog.location.analyze, use, allow
    p, role:default/devportal-admin, scaffolder.task.cancel, use, allow
    p, role:default/devportal-admin, scaffolder.task.create, create, allow
    p, role:default/devportal-admin, scaffolder.task.read, read, allow
    p, role:default/devportal-admin, scaffolder.template.parameter.read, read, allow
    p, role:default/devportal-admin, scaffolder.template.step.read, read, allow
    p, role:default/devportal-admin, scaffolder.action.execute, use, allow
    p, role:default/devportal-admin, policy.entity.read, read, allow
    p, role:default/devportal-admin, policy.entity.create, create, allow
    p, role:default/devportal-admin, policy.entity.delete, delete, allow
    p, role:default/devportal-admin, policy.entity.update, update, allow
    p, role:default/devportal-admin, kong.service.read, read, allow
    p, role:default/devportal-admin, kong.read.available.plugins, read, allow
    p, role:default/devportal-admin, kong.routes.read, read, allow
    p, role:default/devportal-admin, kong.apply.plugins.service, create, allow
    p, role:default/devportal-admin, kong.update.service.plugin, update, allow
    p, role:default/devportal-admin, kong.disable.service.plugin, delete, allow
    p, role:default/devportal-admin, kong.route.create, create, allow
    p, role:default/devportal-admin, kong.route.update, update, allow
    p, role:default/devportal-admin, kong.route.delete, delete, allow
    p, role:default/devportal-admin, kong.apply.plugins.route, create, allow
    p, role:default/devportal-admin, kong.update.route.plugin, update, allow
    p, role:default/devportal-admin, kong.disable.route.plugin, delete, allow
    p, role:default/devportal-admin, kong.read.specs, read, allow
    p, role:default/devportal-admin, kong.update.spec, update, allow
    p, role:default/devportal-admin, cluster.explorer.read, read, allow
    p, role:default/devportal-admin, cluster.explorer.public.environment.read, read, allow
    p, role:default/devportal-admin, gitlab.pipelines.read, read, allow
    p, role:default/devportal-admin, gitlab.pipelines.create, create, allow
    p, role:default/devportal-admin, github.workflows.read, read, allow
    p, role:default/devportal-admin, github.workflows.create, create, allow
    p, role:default/devportal-admin, admin.access.read, read, allow
    p, role:default/devportal-admin, apiManagement.access.read, read, allow

    g, group:default/{{ $adminGroup }}, role:default/devportal-admin
    
{{- end }}