{{- if .Values.permission.rbac.admin.defaultAdminRoleEnabled }}
{{ $adminGroup := .Values.platform.defaultGroups.admin | default "platform-admin" }}
{{ $userGroup := .Values.platform.defaultGroups.user | default "platform-user" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "devportal-charts.fullname" . }}-roles-env"
data:
  rbac-policies: | 
    p, role:default/devportal-admin, catalog-entity, read, allow
    p, role:default/devportal-admin, catalog.entity.create, create, allow
    p, role:default/devportal-admin, policy-entity, read, allow
    p, role:default/devportal-admin, policy-entity, create, allow
    p, role:default/devportal-admin, policy-entity, update, allow
    p, role:default/devportal-admin, policy-entity, delete, allow
    
    p, role:default/devportal-admin, cluster.explorer.read, read, allow
    p, role:default/devportal-admin, cluster.explorer.public.environment.read, read, allow
    p, role:default/devportal-admin, gitlab.pipelines.read, read, allow
    p, role:default/devportal-admin, gitlab.pipelines.create, create, allow
    p, role:default/devportal-admin, github.workflows.read, read, allow
    p, role:default/devportal-admin, github.workflows.create, create, allow
    p, role:default/devportal-admin, admin.access.read, read, allow
    p, role:default/devportal-admin, apiManagement.access.read, read, allow
    p, role:default/devportal-admin, kong.service.manager.read, read, allow
    p, role:default/devportal-admin, kong.service.manager.create, create, allow
    p, role:default/devportal-admin, kong.service.manager.update, update, allow
    p, role:default/devportal-admin, kong.service.manager.delete, delete, allow
    p, role:default/devportal-admin, catalog-entity, delete, allow
    p, role:default/devportal-admin, catalog-entity, update, allow
    p, role:default/devportal-admin, catalog.location.read, read, allow
    p, role:default/devportal-admin, catalog.location.create, create, allow
    p, role:default/devportal-admin, catalog.location.delete, delete, allow
    p, role:default/devportal-admin, scaffolder-template, read, allow
    p, role:default/devportal-admin, scaffolder-action, use, allow
    p, role:default/devportal-admin, scaffolder.task.read, read, allow
    p, role:default/devportal-admin, scaffolder.task.create, create, allow
    p, role:default/devportal-admin, scaffolder.task.cancel, use, allow
    p, role:default/devportal-admin, kubernetes.proxy, use, allow

    g, group:default/{{ $adminGroup }}, role:default/devportal-admin
    
{{- end }}