
{{- if or (and .Values.integrations.github .Values.integrations.github.apps) .Values.githubApp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devportal-charts.fullname" . }}-github-app
data:
    github-app-credentials: |
      {{- if .Values.githubApp }}
      {{- .Values.githubApp | nindent 6 }}
      {{- else }}
      appId: {{ .Values.integrations.github.apps.appId }}
      {{- if .Values.integrations.github.apps.allowedInstallationOwners }}
      allowedInstallationOwners: {{ .Values.integrations.github.apps.allowedInstallationOwners | toJson }}
      {{- end }}
      clientId: {{ .Values.integrations.github.apps.clientId }}
      clientSecret: {{ .Values.integrations.github.apps.clientSecret }}
      webhookSecret: {{ .Values.integrations.github.apps.webhookSecret }}
      privateKey: |
        {{- .Values.integrations.github.apps.privateKey | nindent 10 }}
      {{- end -}}
{{- end -}}