 apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-devportal-read-only
rules:
  - apiGroups:
      - '*'
    resources:
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - horizontalpodautoscalers
      - ingressclasses
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - replicasets
      - services
      - statefulsets
      - resourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-devportal
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-devportal-read-only
roleRef:
  kind: ClusterRole
  name: platform-devportal-read-only
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: platform-devportal
