# .github/workflows/ci.yml
name: CI - Node.js basic quality and security

on:
  push:
    branches:
      - refactor-ci-cd
#   pull_request:
#     branches:
#       - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: yarn install

      - name: Executar testes unitários com coverage
        run: yarn test --coverage
        continue-on-error: true
        env:
          CI: true

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan do repositório com Trivy
        run: |
          trivy fs --exit-code 0 --severity CRITICAL,HIGH --format sarif -o trivy.sarif .
        continue-on-error: true

      - name: Upload do relatório SARIF para a aba de Security do GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
